#!/bin/sh

set -e

# Manually enable and start the systemd service since --with systemd was removed from dh.
if [ -x "/bin/systemctl" ]; then
    systemctl enable country-block.service >/dev/null || true
    systemctl start country-block.service >/dev/null || true
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
    # Run country-block-update for the first time if config.conf exists
    if [ -f "/etc/country-block/config.conf" ]; then
        /usr/sbin/country-block-update || true
    fi
fi

exit 0
