#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    # Remove runtime cache data created by the update script.
    rm -rf "/var/cache/country-block" || true

    # Remove configuration directory if empty
    rmdir --ignore-fail-on-non-empty "/etc/country-block" 2>/dev/null || true
fi

#DEBHELPER#

exit 0
