#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
    # Run country-block update for the first time if config.conf exists
    if [ -f "/etc/country-block/config.conf" ]; then
        country-block update || true
    fi
fi

#DEBHELPER#

exit 0
